"""Adds config

Revision ID: c276d5ad20b3
Revises: 12a41310ec61
Create Date: 2025-09-25 12:11:24.243901

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c276d5ad20b3"
down_revision: str | Sequence[str] | None = "12a41310ec61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "updated_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_config_name"), "config", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_config_name"), table_name="config")
    op.drop_table("config")
    # ### end Alembic commands ###
