"""Adds message models

Revision ID: 12a41310ec61
Revises: 3fb673f632e4
Create Date: 2025-09-25 12:10:55.028832

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12a41310ec61"
down_revision: str | Sequence[str] | None = "3fb673f632e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_group",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "description", sa.String(length=1000), server_default="", nullable=False
        ),
        sa.Column("disabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "updated_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="message",
    )
    op.create_table(
        "message",
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column("disabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "updated_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["message.message_group.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="message",
    )
    op.create_index(
        op.f("ix_message_message_group_id"),
        "message",
        ["group_id"],
        unique=False,
        schema="message",
    )
    op.create_table(
        "message_group_choice",
        sa.Column("snowflake_id", sa.BigInteger(), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "weight",
            sa.Float(),
            server_default="1.0",
            nullable=False,
            comment="Weighted roll choices are weighted between themselves",
        ),
        sa.Column(
            "independent_roll_probability",
            sa.Float(),
            server_default="0.0",
            nullable=False,
            comment="Independent roll choices are rolled before weighted choices",
        ),
        sa.Column(
            "is_channel",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether the snowflake_id refers to a channel",
        ),
        sa.Column(
            "is_user",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether the snowflake_id refers to a user",
        ),
        sa.Column("disabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "updated_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["message.message_group.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snowflake_id", "group_id"),
        schema="message",
    )
    op.create_index(
        op.f("ix_message_message_group_choice_group_id"),
        "message_group_choice",
        ["group_id"],
        unique=False,
        schema="message",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_message_message_group_choice_group_id"),
        table_name="message_group_choice",
        schema="message",
    )
    op.drop_table("message_group_choice", schema="message")
    op.drop_index(
        op.f("ix_message_message_group_id"), table_name="message", schema="message"
    )
    op.drop_table("message", schema="message")
    op.drop_table("message_group", schema="message")
    # ### end Alembic commands ###
