"""adds channel_enabled model

Revision ID: dda3c765cd72
Revises: d6c9b9098c33
Create Date: 2026-01-30 10:08:37.428518

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dda3c765cd72"
down_revision: str | Sequence[str] | None = "d6c9b9098c33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_enabled",
        sa.Column("channel_snowflake_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "updated_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="message",
    )
    op.create_index(
        op.f("ix_message_channel_enabled_channel_snowflake_id"),
        "channel_enabled",
        ["channel_snowflake_id"],
        unique=False,
        schema="message",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_message_channel_enabled_channel_snowflake_id"),
        table_name="channel_enabled",
        schema="message",
    )
    op.drop_table("channel_enabled", schema="message")
    # ### end Alembic commands ###
