"""adds intensity table and drops config

Revision ID: 8832bce77485
Revises: dda3c765cd72
Create Date: 2026-04-18 20:00:09.142423

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8832bce77485"
down_revision: str | Sequence[str] | None = "dda3c765cd72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intensity",
        sa.Column("channel_snowflake_id", sa.BigInteger(), nullable=False),
        sa.Column("intensity", sa.String(length=100), nullable=False),
        sa.Column(
            "created_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "updated_by",
            sa.BigInteger(),
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_intensity_channel_snowflake_id"),
        "intensity",
        ["channel_snowflake_id"],
        unique=True,
    )
    op.drop_index(op.f("ix_config_name"), table_name="config")
    op.drop_table("config")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "updated_by",
            sa.BIGINT(),
            autoincrement=False,
            nullable=False,
            comment="Snowflake id of the user. 0 for legacy.",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("config_pkey")),
    )
    op.create_index(op.f("ix_config_name"), "config", ["name"], unique=False)
    op.drop_index(op.f("ix_intensity_channel_snowflake_id"), table_name="intensity")
    op.drop_table("intensity")
    # ### end Alembic commands ###
